##### Numpy Creation Exercises

1. Write a function to generate a checkerboard n x n matrix using numpy creation function(s) where n is an even number.

e.g  <br>
<u>Input</u> <br>
n  = 8 <br>

<u>Output</u> <br>
[[0 1 0 1 0 1 0 1] <br>
 [1 0 1 0 1 0 1 0] <br>
 [0 1 0 1 0 1 0 1] <br>
 [1 0 1 0 1 0 1 0] <br>
 [0 1 0 1 0 1 0 1] <br>
 [1 0 1 0 1 0 1 0] <br>
 [0 1 0 1 0 1 0 1] <br>
 [1 0 1 0 1 0 1 0]] <br>
 <br>
<center><i>Level: Medium</i></center>

<br>
<br>

2. Write a function to create a n x n matrix with row values starting from 1 and difference between each element in a row is specified by "diff".
<i>where n can take values greater than 3 and "diff" can take values greater than 0.</i>

<center><i>Level: Medium</i></center>

e.g. <br>
<u>Input</u> <br>
n  = 8 <br>
diff = 3 <br>

<u>Output</u> <br>
8 x 8 matrix <br>
[[ 1,  4,  7, 10, 13, 16, 19, 22], <br>
[ 1,  4,  7, 10, 13, 16, 19, 22], <br>
[ 1,  4,  7, 10, 13, 16, 19, 22], <br>
[ 1,  4,  7, 10, 13, 16, 19, 22], <br>
[ 1,  4,  7, 10, 13, 16, 19, 22], <br>
[ 1,  4,  7, 10, 13, 16, 19, 22], <br>
[ 1,  4,  7, 10, 13, 16, 19, 22], <br>
[ 1,  4,  7, 10, 13, 16, 19, 22]] <br>
 <br>
 
 <u>Input</u> <br>
n  = 5 <br>
diff = 2 <br>

<u>Output</u> <br>
5 x 5 matrix <br>
[[1, 3, 5, 7, 9], <br>
[1, 3, 5, 7, 9], <br>
[1, 3, 5, 7, 9], <br>
[1, 3, 5, 7, 9], <br>
[1, 3, 5, 7, 9]] <br>
 <br>
 
 
 <u>Input</u> <br>
n  = 6 <br>
diff = 1 <br>

<u>Output</u> <br>
6 x 6 matrix <br>
[[1, 2, 3, 4, 5, 6], <br>
[1, 2, 3, 4, 5, 6], <br>
[1, 2, 3, 4, 5, 6], <br>
[1, 2, 3, 4, 5, 6], <br>
[1, 2, 3, 4, 5, 6], <br>
[1, 2, 3, 4, 5, 6]] <br>

<br>
<br>

3. Write a program to generate all possible 2D shapes for the given range of values and also convert and print the 2D data of a selected possible shape of the same range.

<center><i>Level: Difficult</i></center>

e.g.(1) <br>
<u>Input (Part 1)</u> <br>
(1,60,4) <br>

<u>Output (Part 1)</u> <br>
possible 2D shapes:<br>
(1,15),(3,5),(5,3),(15,1)<br>

<u>Input (Part 2)</u> <br>
(5,3) <br>
<u>Output (Part 2)</u> <br>
[[1,5,9], <br>
[13,17,21], <br>
[25,29,33], <br>
[37,41,45], <br>
[49,53,57]] <br>


 <br>
 <br>
e.g.(2) <br>
<u>Input (Part 1)</u> <br>
(2,36,3) <br>

<u>Output (Part 1)</u> <br>
possible 2D shapes: <br>
(1,12),(2,6),(3,4),(4,3),(6,2),(12,1) <br>

 <br>
 
 <u>Input (Part 2)</u> <br>
(2,6) <br>

<u>Output (Part 2)</u> <br>
[[2,5,8,11,14,17], <br>
[20,23,26,29,32,35]] <br>

<br>
<br>

4. Write a program to generate random integer values array of size 30 between the given interval "a" and "b"  with both a and b inclusive. Out of this random array, select 3 values at random (call it as "set1").
Generate 12 values between given interval [a, b] with both a and b inclusive,  such that difference between every 2 consecutive value is exactly same. Out of these generated 12 values, select 3 values at random (call it as "set2").

Finally Create 2D result array with these 2 set of selections as rows.

<u>Condition: Chances of occuring same values should be low in the final result</u>

Note: Round off all float values to 2 decimals
<br>
 <br>
<center><i>Level: Medium</i></center> <br>

e.g.(1) <br>
<u>Input</u> <br>
a =60, b= 150 <br>
 <br>
<u>Output (set 1)</u> <br>
[102  80  78] <br>
<u>Output (set 2)</u> <br>
[150.   117.27  60.  ] <br>
<u> Output (Final) </u> <br>
[[102 80 78 <br>
[150.   117.27  60.  ] ] <br>

e.g.(2) <br>
<u>Input</u> <br>
a =15, b= 50 <br>

<u>Output (set 1)</u> <br>
[15 45 17] <br>
<u>Output (set 2)</u> <br>
[40.45 30.91 37.27] <br>
<u> Output (Final) </u> <br>
[[15 45 17]<br>
[40.45 30.91 37.27] ] <br>